from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.exceptions import PermissionDenied
from .models import Interview, Patient, Interviewer, InterviewState
import json
import time


@login_required(login_url='login')
def new_interview(request):
    if request.method == 'POST':
        patient     = Patient.objects.create()
        interviewer = Interviewer.objects.create()
        interview   = Interview.objects.create(
            createdBy  = request.user,
            patient     = patient,
            interviewer = interviewer,
            title       = f"Interview #{Interview.objects.count() + 1}",
        )
        return redirect('chat', interview_id=interview.id)
    return render(request, 'chat/new_interview.html')


@login_required(login_url='login')
def load_user(request):
    interviews = Interview.objects.filter(
        createdBy=request.user
    ).order_by('-createdAt')
    return render(request, 'chat/load_list.html', {
        'interviews': interviews,
        'view': 'mine'
    })


@login_required(login_url='login')
def load_all(request):
    if not request.user.is_staff:
        raise PermissionDenied
    interviews = Interview.objects.all().order_by('-createdAt')
    return render(request, 'chat/load_list.html', {
        'interviews': interviews,
        'view': 'all'
    })


@login_required(login_url='login')
def load_interview(request, interview_id):
    interview = get_object_or_404(Interview, id=interview_id)
    return render(request, 'chat/load_interview.html', {
        'interview': interview
    })


@login_required(login_url='login')
def chat_view(request, interview_id):
    interview = get_object_or_404(Interview, id=interview_id, createdBy=request.user)
    messages  = interview.messages.all()
    interview.is_active = True
    interview.save()
    return render(request, 'chat/chat.html', {
        'interview': interview,
        'messages':  messages,
    })


@login_required(login_url='login')
def send_message(request, interview_id):
    if request.method != 'POST':
        return JsonResponse({'error': 'POST required'}, status=405)
    interview  = get_object_or_404(Interview, id=interview_id, createdBy=request.user)
    user_input = request.POST.get('message', '').strip()
    if not user_input:
        return JsonResponse({'error': 'Empty message'}, status=400)
    interview.messages.create(role='user', content=user_input)
    reply = 'LLM response placeholder'
    interview.messages.create(role='assistant', content=reply)
    interview.state.turn_count += 1
    interview.state.save()
    return JsonResponse({'response': reply})


@login_required(login_url='login')
def end_interview(request, interview_id):
    interview = get_object_or_404(Interview, id=interview_id, createdBy=request.user)
    interview.is_active = False
    interview.save()
    return redirect('load_user')


@login_required(login_url='login')
def generate_field(request):
    if request.method != 'POST':
        return JsonResponse({'error': 'POST required'}, status=405)
    data  = json.loads(request.body)
    field = data.get('field', '')
    deps  = data.get('dependencies', {})
    time.sleep(3)
    return JsonResponse({'value': f'AUTOGENERATED RESPONSE for {field}'})


@login_required(login_url='login')
def patient_list(request):
    """Returns all patients as JSON — supports my_patients filter"""
    only_mine = request.GET.get('mine') == '1'
    qs = Patient.objects.all()
    if only_mine:
        qs = qs.filter(createdBy=request.user)
    qs = qs.order_by('-createdAt')
    data = [{
        'id':         p.id,
        'name':       p.name        or '',
        'age':        p.age         or '',
        'gender':     p.gender      or '',
        'disorder':   p.disorder    or '',
        'occupation': p.occupation  or '',
        'createdBy': p.createdBy.username if p.createdBy else '—',
        'createdAt': p.createdAt.strftime('%Y-%m-%d') if p.createdAt else '',
    } for p in qs]
    return JsonResponse({'patients': data})


@login_required(login_url='login')
def patient_detail(request, patient_id):
    """Returns full patient profile as JSON"""
    p = get_object_or_404(Patient, id=patient_id)
    return JsonResponse({
        'id':                  p.id,
        'name':                p.name,
        'age':                 p.age,
        'gender':              p.gender,
        'ethnicity':           p.ethnicity         if hasattr(p, 'ethnicity') else '',
        'education':           p.education,
        'occupation':          p.occupation,
        'disorder':            p.disorder          if hasattr(p, 'disorder') else '',
        'type':                p.type,
        'base_emotions':       p.base_emotions,
        'history':             p.history,
        'helpless_beliefs':    p.helpless_beliefs,
        'unlovable_beliefs':   p.unlovable_beliefs,
        'worthless_beliefs':   p.worthless_beliefs,
        'intermediate_belief': p.intermediate_belief,
        'coping_strategies':   p.coping_strategies,
        'trigger':             p.trigger,
        'auto_thoughts':       p.auto_thoughts,
        'behavior':            p.behavior,
        'intake':              p.intake,
        'vignette':            p.vignette,
        'family_tree':         p.family_tree,
        'timeline':            p.timeline,
        'createdBy':          p.createdBy.username if p.createdBy else '—',
        'createdAt':          p.createdAt.strftime('%Y-%m-%d') if p.createdAt else '',
    })
