# Generated by Django 6.0.2 on 2026-02-25 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="InterviewState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_count", models.IntegerField(default=0)),
                ("summary_freq", models.IntegerField(default=5)),
                ("summary_turn", models.IntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("patient_summary", models.TextField(blank=True)),
                ("patient_feelings", models.TextField(blank=True)),
                ("patient_behavior", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interviewer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.interviewer",
                    ),
                ),
                (
                    "state",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.interviewstate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("patient", "Patient"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.interview",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("ethnicity", models.CharField(blank=True, max_length=50)),
                ("education", models.CharField(blank=True, max_length=200)),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("disorder", models.TextField(blank=True)),
                ("type", models.JSONField(blank=True, default=list)),
                ("history", models.TextField(blank=True)),
                ("helpless_beliefs", models.JSONField(blank=True, default=list)),
                ("unlovable_beliefs", models.JSONField(blank=True, default=list)),
                ("worthless_beliefs", models.JSONField(blank=True, default=list)),
                ("intermediate_belief", models.TextField(blank=True)),
                ("coping_strategies", models.TextField(blank=True)),
                ("trigger", models.TextField(blank=True)),
                ("auto_thoughts", models.TextField(blank=True)),
                ("base_emotions", models.JSONField(blank=True, default=list)),
                ("behavior", models.TextField(blank=True)),
                ("intake", models.TextField(blank=True)),
                ("vignette", models.TextField(blank=True)),
                ("family_tree", models.TextField(blank=True)),
                ("timeline", models.TextField(blank=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interview",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="chat.patient"
            ),
        ),
    ]
