# Generated by Django 6.0.2 on 2026-02-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="history",
        ),
        migrations.AddField(
            model_name="patient",
            name="childhood_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="education_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="occupation_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="personal_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="relationship_history",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
