# Generated by Django 6.0.2 on 2026-02-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_patient_history_patient_childhood_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="profile_summary",
            field=models.TextField(blank=True),
        ),
    ]
