# Generated by Django 6.0.2 on 2026-02-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_patient_profile_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="marital_status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
