# Generated by Django 6.0.2 on 2026-02-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_patient_marital_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="session_history",
            field=models.TextField(blank=True),
        ),
    ]
