# Generated by Django 6.0.2 on 2026-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_patient_session_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_psi",
            field=models.BooleanField(default=False),
        ),
    ]
