# Generated by Django 6.0.2 on 2026-03-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_patient_patient_psi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="chat.patient",
            ),
        ),
    ]
