# Generated by Django 6.0.2 on 2026-03-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_interview_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewer",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
