# Generated by Django 6.0.2 on 2026-03-02 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_patient_id_chatsettings_newsessionsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsettings",
            name="interview",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatSettings",
                to="chat.interview",
            ),
        ),
        migrations.AlterField(
            model_name="newsessionsettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newSessionSettings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
