# Generated by Django 6.0.2 on 2026-03-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_alter_chatsettings_interview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="behavior",
            field=models.TextField(blank=True),
        ),
    ]
