# Generated by Django 6.0.2 on 2026-03-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_message_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsessionsettings',
            name='max_tokens',
            field=models.IntegerField(default=16384),
        ),
    ]
