# Generated by Django 6.0.2 on 2026-03-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_newsessionsettings_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='children',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='grandchildren',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
