# Generated by Django 6.0.2 on 2026-03-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_patient_children_patient_grandchildren'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='canonical_facts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='impact',
            field=models.TextField(blank=True),
        ),
    ]
